apify/impit

.github/workflows/cli-release.yaml, impit/src/response_parsing/mod.rs
=> fix(js): use replacement character on invalid decode

Cargo.lock, impit-node/test/basics.test.ts
The Node `impit` tests were rather minimalistic and targetting only the most basic use-cases.
This PR adds more test cases and a matrix of different HTTP methods / impersonated browsers to run the tests with.
=> chore(js): add more tests

impit-node/package.json, impit-node/yarn.lock
Solves Dependabot security warnings.
=> chore: bump `vitest` version

Cargo.lock
Solves Dependabot security warnings
=> chore: update lockfile with `cargo update`

impit-node/package.json
Uses the new (canary) `@napi-rs/cli` arguments. GH Release creation is now opt-in with the `--gh-release` flag.
=> chore: conform to the new NAPI CLI

impit-node/package.json, impit-node/test/basics.test.ts
Adds retries and longer timeouts, which should help with the flaky HTTPBin tests.
=> chore: make HTTPBin tests more stable

.github/workflows/node-release.yaml
Fixes the NPM release pipeline (failing with `yarn` version mismatch now)
=> chore(ci): use `yarn@v4` in NPM publish step

.github/workflows/node-test.yaml, impit-node/index.d.ts, impit-node/src/response.rs, impit-node/test/basics.test.ts, impit-node/yarn.lock
Adds [Response.url](https://developer.mozilla.org/en-US/docs/Web/API/Response/url) property to the `ImpitResponse` struct / object.
=> feat(js): add `.url` field to `impit-node` Response

impit-node/yarn.lock
Closes Dependabot security warnings.
=> chore: regenerate Node.JS lockfile with latest dependencies

impit-node/index.wrapper.js, impit-node/package.json, impit-node/yarn.lock
Renames native code import to mitigate naming collision with global `exports`.
=> fix(js): allow `impit` usage from ESM

impit-node/index.wrapper.js, impit-node/test/basics.test.ts
Lists the "named" exports from the `impit` package verbatim so they can be imported with
```typescript
import { Impit } from 'impit'; 
```
from ESM packages without causing the following error:
```
import { Impit } from "impit";
^^^^^
SyntaxError: Named export 'Impit' not found. The requested module 'impit' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
import pkg from 'impit';
const { Impit } = pkg;
```
=> fix(js): enable ESM named imports from `impit` packages

.github/workflows/cli-release.yaml
Reenable [uploading run artifacts](https://github.com/houseabsolute/actions-rust-release/blob/48ce35fb40c3dab00791a3d6c485022341354c44/action.yml#L148) for the CLI build action. Change the required tag prefix to mitigate triggering CLI builds on
=> chore(ci): upload artifacts on CLI build

.github/workflows/cli-release.yaml, .github/workflows/python-test.yaml
Runs only CLI-related tests in the CLI workflow and disables time-consuming builds of Python bindings if there were no changes to the relevant code.
=> chore(ci): run relevant tests in CLI workflow

Cargo.lock, impit/Cargo.toml, impit/src/impit.rs
Adds `std::error::Error` implementation with `thiserror`. This should improve the developer experience and error messages across the monorepo.
Closes #84
=> feat: use `thiserror` for better error handling DX

impit-node/npm/linux-arm64-gnu/package.json, impit-node/npm/linux-arm64-musl/package.json
Followup to #94 , the `impit-linux-arm64-(gnu|musl)` published packages didn't have the native binary included due to naming mismatch.
=> fix(js): bundle native binary in `linux-arm64` packages

Cargo.lock, impit-python/Cargo.toml, impit-python/src/async_client.rs, impit-python/src/client.rs, impit-python/src/lib.rs, impit-python/src/request.rs, impit-python/test/async_test.py, impit-python/test/basic_test.py
Following the discussion under #97 , this PR widens the type accepted by the `data` parameter.
`data` now accepts both a `dict[str,str]` and a binary representation of the request body. This PR intentionally doesn't update the recently added typings in the `impit.pyi` file, as this behaviour (accepting the binary body) is considered deprecated in the `httpx` library we use as the design master.
=> feat(py): allow passing binary body to the `data` parameter

.github/workflows/python-test.yaml, impit-python/pyproject.toml, impit-python/test/basic_test.py, impit-python/uv.lock
Uses state-of-the-art package manager for Python and installs the test dependencies in CI from the `pyproject.toml` file, to ensure all the required Python deps are present in test-time.
=> chore(python): rerun flaky CI tests, use `uv` in CI

Cargo.lock, impit-python/Cargo.toml
Updates Rust dependencies for the `pyo3`-related tooling.
=> chore(py): bump `pyo3` and dependencies

Cargo.lock, impit-python/src/response.rs, impit-python/test/basic_test.py, impit/Cargo.toml, impit/src/response_parsing/mod.rs
Parses the `content-type` header for the `charset` parameter.
Closes #109 
Note that the response encoding in `impit` is still not on par with `httpx`, which accepts encoding as parameter, or "autodetect" functions ([docs here](https://www.python-httpx.org/advanced/text-encodings/))
=> fix(py): `response.encoding` contains the actual encoding

Cargo.lock, impit-python/Cargo.toml, impit-python/python/impit/impit.pyi, impit-python/src/async_client.rs, impit-python/src/client.rs, impit-python/src/lib.rs, impit-python/src/response.rs, impit-python/test/async_test.py, impit-python/test/basic_test.py, impit-python/test/httpbin.py, impit/src/lib.rs, impit/src/response_parsing/mod.rs
- add `url` property for `Response`
- add `content` property for `Response`
=> feat(py): add `url` and `content` property for `Response`, smart `.text` decoding, options for redirects 

impit-node/test/basics.test.ts, impit-python/test/async_test.py, impit-python/test/basic_test.py, impit/src/http_headers/mod.rs
Refactors and simplifies the custom header logic. Custom headers now override "impersonated" browser headers regardless on the (upper|lower)case.
closes #96
=> fix: case-insensitive request header deduplication

.github/workflows/python-release.yaml, impit-python/test/async_test.py, impit-python/test/basic_test.py
Switch from the maturin-based non-standard tooling to the `pypa/gh-action-pypi-publish` action we use in other Apify Python packages.
=> chore: use OIDC-autheticated PyPI publishing action

impit-node/index.d.ts, impit-node/src/response.rs, impit-node/test/basics.test.ts
The type definitions for `response.text()` return type used `String` (see capital S) instead of `string` (like `fetch` API does). Note that this is a strictly type-level issue and simple cast (or type change, in this case) solves this.
Closes #135
=> fix: set `response.text()` return type to `string`

.github/workflows/cli-release.yaml
Unblocks the CLI release CI workflow after the Ubuntu 20.04 runner deprecation.
=> chore: bump `ubuntu` version in CI

impit-node/index.d.ts, impit-node/package.json, impit-node/src/impit_builder.rs
Switches from exporting `const enum`s from the `.d.ts` file ([which is problematic](https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls)) to exporting union types. 
Makes the `browser` option accept lowercase browser names.
Closes #133
=> fix(js): do not publish ambient `const enum`s

impit-cli/src/headers.rs, impit-node/index.d.ts, impit-node/index.wrapper.js, impit-node/src/request.rs, impit-node/test/basics.test.ts, impit-python/src/async_client.rs, impit-python/src/client.rs, impit/src/http_headers/mod.rs, impit/src/request.rs
Allows sending multiple request headers of the same name across all bindings / tools.
Broadens the `RequestInit.headers` type in the `impit-node` bindings. Closes #151
=> feat: switch to `Vec<(String, String)>` for request headers

.github/workflows/node-test.yaml
Downgrades the CI runners to Ubuntu 22 to compile against older GLIBC (where Docker-based build is not used).
closes #106
=> chore: downgrade CI runners to ensure better GLIBC compatibility

impit-node/index.wrapper.js, impit-node/package.json, impit-node/yarn.lock
Wraps the original `napi-rs` ENOENT error with a more descriptive error message. Understands `IMPIT_VERBOSE` envvar for printing the original error message.
=> fix: render helpful error message on import errors

impit/src/errors.rs
Improve error logs in bindings by tunneling the lower-level `reqwest` errors through to binding users.
=> feat: show the underlying `reqwest` error on unrecognized error type

impit-node/Cargo.toml, impit-node/index.d.ts, impit-node/package.json, impit-node/src/response.rs, impit-node/test/basics.test.ts, impit-node/yarn.lock
Adds new `response.arrayBuffer` method ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response/arrayBuffer)) and implements `response.bytes` using `arrayBuffer()` to improve compatibility with Node < 22 (`.bytes()` support was rather experimental until this version).
=> feat(js): add `resp.arrayBuffer`, improve Node <22 compatibility

impit-node/index.wrapper.js, impit-node/package.json, impit-node/test/basics.test.ts, impit-node/yarn.lock
Removes parameter reassignment code smell. Fixes errors on `null` (or other nullish, but not expected) body.
=> fix(js): support `null` request payload, don't modify options

Cargo.lock, impit-node/Cargo.toml, impit-node/package.json, impit-node/src/impit_builder.rs, impit-node/src/request.rs, impit-node/src/response.rs, impit-node/yarn.lock
Memory leak in `napi-rs`'s implementation of `ReadableStream` was causing `impit` to leak small amounts of memory on response read (`.text()`, `.json()`, `.bytes()` etc.).
This PR bumps the `napi-rs` version to the latest beta, where the memory leak cause is fixed.
=> fix(js): solve memory leak on response read

impit-python/src/errors.rs, impit/src/errors.rs
Injects `cause` to the `ConnectError` display string. This allows for better error introspection in dependent packages.
Unblocks https://github.com/apify/crawlee-python/pull/1389/
=> feat: include error message in `ConnectError`
